/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mergeSort;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());

        int arr[] = {5,-12,3,8,16,20,19};

        MergeSort mergeSort = new MergeSort();
        mergeSort.mergeSort(arr);

    }


}
