/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mergeSort;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public void mergeSort(int[] arr){
        int n = arr.length;

        if(n>1){
            int mid = arr.length/2;
            int left = Arrays.copyOfRange(int[] left, 0, mid);
            int right = Arrays.copyOfRange(int [] right, mid, arr.length);

            mergeSort(left);
            mergeSort(right);
            merge(left, right, arr);
        }
    }

    public void merge(int[] left, int[] right, int[] arr){
        int i = 0;
        int j = 0;
        int k = 0;

        while (i < left.length && j < right.length){
            if(left[i]<=right[j]){
                arr[k] = left[i];
                i = i+1;
            } else{
                arr[k] = right[j];
                j = j+1;
            }
            k = k+1;
        }
        if (i == left.length){
            while (i < right.length){
                arr[k] = right[i];
                k++;
                i++;
            }
        }else {
            while (j < left.length){
                arr[k] = left[j];
                k++;
                j++;
            }
        }
    }
}
