/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception{
        System.out.println(new App().getGreeting());


        Graph<String> graph = new Graph<>();
        Node<String> node1 = graph.add("Pandora");
        Node<String> node2 = graph.add("Arendelle");
        Node<String> node3 = graph.add("Metroville");
        Node<String> node4 = graph.add("Monstroplolis");
        Node<String> node5 = graph.add("Narnia");
        Node<String> node6 = graph.add("Naboo");
        graph.addEdge(node1, node2);
        graph.addEdge(node2, node3);
        graph.addEdge(node2, node4);
        graph.addEdge(node3, node4);
        graph.addEdge(node3, node5);
        graph.addEdge(node3, node6);
        graph.addEdge(node5, node6);
        graph.addEdge(node4, node6);
//        graph.breadthFirst(node1);
    }
}
