/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QuickSort;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());
        int[] arr = {15,22,-18,9,2,4,17,5};
        QuickSort quickSort = new QuickSort();
        quickSort.QuickSortMethod(arr, 0, arr.length-1);
    }
}
