/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashMap;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        BinaryTree binaryTree = new BinaryTree();

        binaryTree.setRoot(new Node(5));

        binaryTree.getRoot().setLeft(new Node(3));
        binaryTree.getRoot().getLeft().setLeft(new Node(1));
        binaryTree.getRoot().getLeft().setRight(new Node(4));

        binaryTree.getRoot().setRight(new Node(7));
        binaryTree.getRoot().getRight().setLeft(new Node(6));
        binaryTree.getRoot().getRight().setRight(new Node(9));

    }
}
