/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTable;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
//
//        char ch = 'c';
//        char ch1 = 'C';
//        int ascii = ch;
//        int ascii1 = ch1;
        String string = "Miral";
//        System.out.println("ASCII of c = " + ascii);
//        System.out.println("ASCII of C = " + ascii1);
//        String arrayOfStrings = Arrays.toString(string.split("")).toLowerCase();

    }
}
