/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTable;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());


        HashTableClass hashTableClass = new HashTableClass();
        hashTableClass.HashTable(10);
        hashTableClass.add("abc", "Hello");
        hashTableClass.get("abc");
        hashTableClass.contains("abc");

    }
}
