/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertion.sort;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());
        int[] arr = {5,-12,23,-4,8,9,27,19,7,0,-1};
        InsertionSort insertionSort = new InsertionSort();
        insertionSort.insertionSort(arr);
    }
}
