/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        LinkedList newItem = new LinkedList();
        LinkedList list1 = new LinkedList();
        LinkedList list2 = new LinkedList();

        newItem.insert(2);
        newItem.insert(3);
        newItem.insert(6);
        newItem.insert(5);
        newItem.insert(12);
        newItem.insert(32);
        newItem.append(25);

        list1.append(1);
        list2.append(5);
        list1.append(3);
        list2.append(9);
        list1.append(2);
        list2.append(4);

        newItem.includes(5);
        newItem.includes(2);
        newItem.includes(100);

        newItem.zipLists(list1, list2);


        newItem.insertBefore(5,36);

        newItem.insertAfter(6,49);

        newItem.toString();

//        newItem.kthFromEnd(9);
//        newItem.kthFromEnd(9);
//        newItem.kthFromEnd(1);
        newItem.kthFromEnd(0);
    }
}
