/*
 * This Java source file was generated by the Gradle 'init' task.
 */



public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        LinkedList newItem = new LinkedList();
        newItem.insert(2);
        newItem.insert(3);
        newItem.insert(6);
        newItem.insert(5);
        newItem.insert(12);
        newItem.insert(32);
        newItem.append(25);

        newItem.includes(5);

        newItem.insertBefore(5,36);

        newItem.insertAfter(6,49);

        newItem.toString();

//        newItem.kthFromEnd(8);
//        newItem.kthFromEnd(9);
//        newItem.kthFromEnd(1);
        newItem.kthFromEnd(0);

    }
}
