/*
 * This Java source file was generated by the Gradle 'init' task.
 */



public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        LinkedList newItem = new LinkedList();
        newItem.insert(2);
        newItem.insert(3);
        newItem.insert(6);
        newItem.insert(5);
        newItem.insert(12);


        newItem.includes(5);
        newItem.includes(20);
        newItem.includes(32);

        newItem.toString();
    }
}
