/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QuickSort;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }


    //Happy Path
//    @Test void testMergeSort() throws Exception {
//        int arr[] = {5,-12,3,8,16,20,19};
//
//        QuickSort quickSort = new QuickSort();
//        assertEquals(8, quickSort.QuickSortMethod(arr, 0, arr.length-1)[3]);
//    }

    //Expected Failure || Edge case
    @Test void testTheTheMethodDivideAndConquer() throws Exception {
        int arr[] = new int[0];

        QuickSort quickSort = new QuickSort();
        Assertions.assertThrows(Exception.class, ()->{
            quickSort.QuickSortMethod(arr, 0, arr.length-1);
        });

    }
}
